### ISSUE TITLE
Estruturando o projeto

### ISSUE THREAD

**Issue by Pedrinhown** [PedroPort3s/Caca-Curso#10]
- [x] Definindo as tarefas no github
- [x] Desenvolvimento do back-end em node.js
- [x] Criação de projeto react native utilizando expo 
- [x] Criação da base de dados em MySql
- [x] Definição da identidade visual do projeto
