### ISSUE TITLE
Permitir o usuário favoritar cursos

### ISSUE THREAD

**Issue by Skipperhc** [PedroPort3s/Caca-Curso#13]
- [x] Criar o componente visual para a função favoritar
- [x] Criar a função no back-end para favoritar o curso
- [x] Criar o banco de dados para armazenar cursos favoritos
