### ISSUE TITLE
Permitir o usuário avaliar com gostei/não gostei

### ISSUE THREAD

**Issue by PedroPort3s** [PedroPort3s/Caca-Curso#7]
- [x] Criar o componente visual para a função favoritar
- [x] Criar a função no back-end para favoritar o curso
- [x] Criar o banco de dados para armazenar cursos favoritos
