### ISSUE TITLE
Implementar login via provedores externos

### ISSUE THREAD

**Issue by Pedrinhown** [PedroPort3s/Caca-Curso#9]
- [x] Implementar login com o Google
- [x] Implementar login com a Apple
- [x] Implementar login com o Facebook
- [x] Gravar os dados do usuário no banco de dados
- [x]  Utilizar AsyncStorage para manter informações do usuário logado em cache no dispositivo
